import { Poppins, Bree_Serif, Actor } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["500"],
})
const breeSerif = Bree_Serif({
  variable: "--font-breeSerif",
  weight: ["400"],
})
const actor = Actor({
  variable: "--font-actor",
  weight: ["400"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${actor.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
